### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by bdwyer2** [CODAIT/magicat#1]
I see a strange result when I run `magicat dog-human.jpg --show dog` on the file in the MAX-Object-Detector assets directory.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/19673623/48512262-ed677780-e80d-11e8-8bce-71e8f360ba00.png">

The image looks normal when I run it directly though MAX-Image-Segmenter.
<img width="156" alt="image" src="https://user-images.githubusercontent.com/19673623/48512378-30c1e600-e80e-11e8-807f-a35e12c81419.png">

**Comment by bdwyer2** [comment]
The file I used:

![dog-human](https://user-images.githubusercontent.com/19673623/48516414-299fd580-e818-11e8-9559-6e859eacdc6b.jpg)

**Comment by kastentx** [comment]
Thanks for uploading the test image @bdwyer2 I'll take a look

**Comment by kastentx** [comment]
![doggy-test-no-background](https://user-images.githubusercontent.com/8978592/52153503-ea776880-263f-11e9-91c8-6a87658d1926.png)

Thanks again @bdwyer2 for helping me spot this 🐛
