### ISSUE TITLE
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32

### ISSUE THREAD

**Issue by patrickelectric** [CODAIT/magicat#10]
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32

**Comment by vabarbosa** [comment]
@patrickelectric thanks for catching the issue. one of the dependencies fell a little behind. i have submitted the updates. if you re-install with the latest should hopefully be all set. let me know if you have any questions or run into further issues

**Comment by patrickelectric** [comment]
Everything is working fine now, thanks!
![image](https://user-images.githubusercontent.com/1215497/80631302-e8ab7900-8a2b-11ea-9e22-c7e690a712e4.png)

**Comment by vabarbosa** [comment]
@patrickelectric just wanted to give you a head's up.

i have just pushed some long overdue updates. the biggest change is the `magicat` NPM module has been replaced with `@codait/magicat`  NPM module. you can continue using `magicat` module but when you get the opportunity you should consider switching to the `@codait/magicat` module.

in addition, the CLI got some refactoring (e.g., `--show` renamed to `--preview`). you can check out the updated [README](https://github.com/CODAIT/magicat/blob/master/README.md) to see some of the changes or just run `magicat --help` in the updated CLI.

any comments or feedback is welcomed.
