### ISSUE TITLE
Improve error output for invalid input images

### ISSUE THREAD

**Issue by ptitzler** [CODAIT/magicat#5]
One of my directories contains a number of files with a jpg or png extension.

```
magicat ~/Downloads/
Scanning directory '/Users/patti/Downloads'...

error building response map - error preprocessing image - Error: Could not find MIME for Buffer <null>
```

Turns out, one of the files, e.g. `abc.jpg`, wasn't an actual image but a text document. It took me a while to figure out which file was causing the issue. If an error is raised the message should identify the image that was causing it, to make it easier to troubleshoot in situations where `magicat` is used to process a large collection of images.

**Comment by vabarbosa** [comment]
resolved in PR #11 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/13156555/80677670-4a4d0100-8a87-11ea-9b2e-a8a04705bc0f.png">
